### ISSUE TITLE
Problems converging with BBLeuning

### ISSUE THREAD

**Issue by jessicaguo** [RemkoDuursma/plantecophys#2]
Hi there,
I'm trying to obtain BBLeuning parameters in addition to BB and Medlyn stomatal parameters. The nls function within fitBB is not able to converge, as step sizes go below the minimum threshold. The data I'm using were collected indoors with VPD set to 1.5 kPa, so I'm suspecting that there just isn't enough VPD variability to fit the model. Does that seem about right to you?  Are there other avenues I should try?
Thanks!
Jessica

**Comment by moturoa** [comment]
If you don't have enough variability in either A (as a result of T or PPFD) or VPD, the fit may simply not converge. Nothing you can do about it unfortunately! In that case you should consider using the BBOpti model, since it has only two parameters, not three like Leuning, and will 'always' converge.

**Comment by RemkoDuursma** [comment]
If you don't have much variability in VPD then the Leuning model has trouble converging because it has three parameters (and D0 is the bottleneck in case of VPD). If it works for your situation you should consider the BBOpti model since it has only 2 parameters and will 'always' converge.

**Comment by jessicaguo** [comment]
The BBL model is used in ED2,  so I need the Leuning parameters rather than the Medlyn ones. One way other ED2 users have done this is to fix D0 to a default value, e.g., 1.67 kPa as cited in Dewar 2002. 

Would it be okay to submit a PR with an option in D0 to set D0?

**Comment by RemkoDuursma** [comment]
That would be OK but please do so on bitbucket.org/remkoduursma/plantecophys, that is actually the main repository for this project. github is only a mirror. thanks!
